# Generated by Django 2.2.7 on 2019-11-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('time_desc', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '下线')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '下线')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=12)),
                ('pay_type', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pay_time', models.DateTimeField(null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.User')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='BibleStudyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.User')),
            ],
        ),
        migrations.CreateModel(
            name='BibleStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
    ]
