# Generated by Django 2.2.7 on 2019-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('churchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='vunue',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='churchs.Venue', verbose_name='场地'),
        ),
    ]
