# Generated by Django 2.2.7 on 2019-11-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='content',
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.User')),
            ],
        ),
    ]
