# Generated by Django 2.2.7 on 2019-12-04 04:13

import church.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churchs', '0002_auto_20191204_1213'),
        ('church', '0002_auto_20191204_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('video', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='视频')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='BibleStudyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Member')),
            ],
        ),
        migrations.CreateModel(
            name='BibleStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
            ],
        ),
    ]
