# Generated by Django 2.2.7 on 2019-11-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20191127_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='church',
        ),
    ]
