# Generated by Django 2.2.7 on 2019-12-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_biblestudy_biblestudycomment_course_meeting_speaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblestudy',
            options={'verbose_name': '灵修'},
        ),
        migrations.AlterModelOptions(
            name='biblestudycomment',
            options={'verbose_name': '灵修评论'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '聚会'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': '讲员'},
        ),
    ]
