# Generated by Django 2.2.7 on 2019-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_remove_course_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadImages', verbose_name='图片'),
        ),
    ]
