# Generated by Django 2.2.7 on 2019-12-15 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0003_church_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageruser', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='church',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatoruser', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
