# Generated by Django 2.2.7 on 2019-12-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
