# Generated by Django 2.2.7 on 2019-12-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20191209_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblestudy',
            options={'verbose_name': '灵修', 'verbose_name_plural': '灵修'},
        ),
        migrations.AlterModelOptions(
            name='biblestudycomment',
            options={'verbose_name': '灵修评论', 'verbose_name_plural': '灵修评论'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '聚会', 'verbose_name_plural': '聚会'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': '讲员', 'verbose_name_plural': '讲员'},
        ),
    ]
