# Generated by Django 2.2.7 on 2019-12-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20191215_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='vunue',
            new_name='venue',
        ),
    ]
