# Generated by Django 2.2.7 on 2019-12-02 04:29

import church.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_privatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='图片'),
        ),
    ]
