# Generated by Django 2.2.7 on 2019-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
