# Generated by Django 2.2.7 on 2019-12-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20191202_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='发布时间'),
        ),
    ]
