# Generated by Django 2.2.7 on 2019-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20191127_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='标题'),
        ),
    ]
