# Generated by Django 2.2.7 on 2020-01-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0018_auto_20200107_1129'),
        ('church', '0006_auto_20200104_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
