# Generated by Django 2.2.7 on 2019-12-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20191202_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='status',
            field=models.IntegerField(choices=[(1, '草稿'), (2, '发布')], default=1),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
