# Generated by Django 2.2.7 on 2019-12-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_auto_20191202_1305'),
        ('church', '0004_delete_document'),
    ]

    operations = [
    ]
