# Generated by Django 2.2.7 on 2020-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
