# Generated by Django 2.2.7 on 2020-01-12 13:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AlterField(
            model_name='church',
            name='venue',
            field=models.ManyToManyField(blank=True, default=None, to='churchs.Venue', verbose_name='场地'),
        ),
        migrations.AlterField(
            model_name='course',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会或平台'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='course',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='描叙'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker', verbose_name='讲员'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
