# Generated by Django 2.2.7 on 2019-12-02 15:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_merge_20191202_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='church',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PrivateDocument',
        ),
    ]
