# Generated by Django 2.2.7 on 2020-01-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_auto_20200112_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会或平台，默认是用户所在的组织'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='描叙'),
        ),
        migrations.AlterField(
            model_name='course',
            name='speaker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker', verbose_name='讲员'),
        ),
    ]
