# Generated by Django 2.2.7 on 2020-01-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0022_auto_20200112_2217'),
        ('church', '0011_auto_20200118_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='speaker',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker', verbose_name='讲员'),
        ),
    ]
