# Generated by Django 3.0.3 on 2020-02-16 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_manual_20200216_1456'),
        ('church', '0012_auto_20200118_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='iap_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.IAPCharge', verbose_name='内购价格'),
        ),
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.CharField(default='086-010-0001', help_text='只能含有字母，数字, _和-, 不要超过 254个字符', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='代码'),
        ),
    ]
