# Generated by Django 3.0.3 on 2020-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sales_num',
            field=models.IntegerField(default=0),
        ),
    ]
