# Generated by Django 2.2.7 on 2020-03-27 03:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0018_auto_20200309_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.CharField(default='086-010-0001', help_text='只能含有字母，数字, _和-, 不要超过 254个字符', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='代码'),
        ),
        # migrations.AlterField(
        #     model_name='church',
        #     name='promot_cover',
        #     field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_company', to=settings.FILER_IMAGE_MODEL, verbose_name='海报封面'),
        # ),
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='courses', through='payment.Users_Courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
