# Generated by Django 2.2.7 on 2020-04-06 03:59

import church.alioss_storage_backends_v2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_auto_20200327_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='giving_qrcode',
            field=models.FileField(blank=True, null=True, storage=church.alioss_storage_backends_v2.AliyunMediaStorage(), upload_to='', verbose_name='奉献二维码'),
        ),
        migrations.AlterField(
            model_name='church',
            name='promot_cover',
            field=models.FileField(blank=True, null=True, storage=church.alioss_storage_backends_v2.AliyunMediaStorage(), upload_to='', verbose_name='海报封面'),
        ),
    ]
