# Generated by Django 2.2.7 on 2020-04-06 04:00

import church.alioss_storage_backends_v2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_auto_20200406_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='giving_qrcode',
            field=models.ImageField(blank=True, null=True, storage=church.alioss_storage_backends_v2.AliyunMediaStorage(), upload_to='', verbose_name='奉献二维码'),
        ),
        migrations.AlterField(
            model_name='church',
            name='promot_cover',
            field=models.ImageField(blank=True, null=True, storage=church.alioss_storage_backends_v2.AliyunMediaStorage(), upload_to='', verbose_name='海报封面'),
        ),
    ]
