# Generated by Django 2.2.7 on 2020-04-24 07:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_auto_20200414_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.CharField(default='086-010-0001', help_text='只能含有字母，数字, _和-, 不要超过 254个字符', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='代码'),
        ),
    ]
