# Generated by Django 2.2.7 on 2020-05-22 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0023_auto_20200522_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatoruser', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='church',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageruser', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
