# Generated by Django 2.2.7 on 2020-05-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_auto_20200522_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': '教会基本信息', 'verbose_name_plural': '教会基本信息'},
        ),
    ]
