# Generated by Django 2.2.7 on 2020-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0025_auto_20200527_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='giving_qrcode',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='奉献二维码'),
        ),
        migrations.AlterField(
            model_name='church',
            name='promot_cover',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='海报封面'),
        ),
        migrations.AlterField(
            model_name='church',
            name='promot_video',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='海报短片'),
        ),
    ]
