# Generated by Django 2.2.7 on 2020-06-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0053_church_lord_column'),
        ('church', '0026_auto_20200529_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='Lord_Day_column',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lord_Day_column', to='churchs.ContentColumn', verbose_name='教会主日专栏'),
        ),
    ]
