# Generated by Django 2.2.7 on 2020-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0053_church_lord_column'),
        ('church', '0027_church_lord_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='Lord_Day_swipe',
            field=models.ManyToManyField(default=None, null=True, related_name='Lord_Day_swipe', to='churchs.Media', verbose_name='教会主日Banner'),
        ),
    ]
