# Generated by Django 2.2.7 on 2019-12-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20191215_1201'),
        ('users', '0004_auto_20191215_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
    ]
