# Generated by Django 3.0.3 on 2020-02-15 16:59


from django.db import migrations
from payment.models import IAPPrice
import csv


#添加事务？
def forwards_func(apps, schema_editor):
    # init iap_price
    with open('payment/iap_price.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            p = IAPPrice(code=row['Code'],
                         price=row['Price_CNY'],
                         proceeds=row['Proceeds_CNY'],
                         price_usd=row['Price_USD'],
                         proceeds_usd=row['Proceeds_USD'])
            p.save()

    # init iap_charge   
    IAPPricem = apps.get_model("payment", "IAPPrice")
    p1 = IAPPricem.objects.get(code="Tier 2")
    p2 = IAPPricem.objects.get(code="Tier 15")
    p3 = IAPPricem.objects.get(code="Tier 66")
    p4 = IAPPricem.objects.get(code="Tier 81")

    IAPCharge = apps.get_model("payment", "IAPCharge")
    db_alias = schema_editor.connection.alias
    IAPCharge.objects.using(db_alias).bulk_create([

        IAPCharge(price_code=p1, product_id="com.church_platform.iap.12", desc="12元课程"),
        # 客户端根据price_code计算在apple上的product_id
        IAPCharge(price_code=p2, product_id="com.church_platform.iap.98", desc="98元课程"),
        IAPCharge(price_code=p3, product_id="com.church_platform.iap.998", desc="998元课程"),
        IAPCharge(price_code=p4, product_id="com.church_platform.iap.2998", desc="2998元课程"),
    ])


#如何执行reverse？
def reverse_func(apps, schema_editor):
    IAPCharge = apps.get_model("payment", "IAPCharge")
    db_alias = schema_editor.connection.alias
    IAPCharge.objects.using(db_alias).filter(product_id="com.church_platform.iap.12").delete()
    IAPCharge.objects.using(db_alias).filter(product_id="com.church_platform.iap.98").delete()
    IAPCharge.objects.using(db_alias).filter(product_id="com.church_platform.iap.998").delete()
    IAPCharge.objects.using(db_alias).filter(product_id="com.church_platform.iap.2998").delete()

    print("----------")

    IAPPricem = apps.get_model("payment", "IAPPrice")
    db_alias = schema_editor.connection.alias
    IAPPricem.objects.using(db_alias).bulk_delete() #语法是否错误？？？


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
