# Generated by Django 3.0.3 on 2020-02-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0013_auto_20200216_1706'),
        ('payment', '0002_manual_20200216_1456'),
    ]

    def forwards_func(apps, schema_editor):
        PayType = apps.get_model("payment", "PayType")
        db_alias = schema_editor.connection.alias
        PayType.objects.using(db_alias).bulk_create([
            PayType(id=1, name="apple iap"),
            PayType(id=2, name="paypal"),
            PayType(id=3, name="wechat"),
            PayType(id=4, name="alipay"),
        ])
        
    operations = [
        migrations.AlterField(
            model_name='iapcharge',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='人民币价格'),
        ),
        
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),

        migrations.RunPython(forwards_func),
    ]
