# Generated by Django 3.0.3 on 2020-02-29 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0014_auto_20200229_1726'),
        ('payment', '0003_manual_20200222_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.UUIDField(db_index=True, default=uuid.UUID('c2f76e45-e4e9-4380-a3bd-bd0ff6c2920e'), editable=False, unique=True, verbose_name='订单号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='人民币价格')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='美元价格')),
                ('is_sandbox', models.BooleanField()),
                ('iap_receipt', models.TextField(verbose_name='内购支付凭证')),
                ('pp_transcation_id', models.CharField(max_length=255, verbose_name='paypal交易id')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '支付失败')], default=0, verbose_name='状态')),
                ('desc', models.CharField(max_length=255, verbose_name='备注')),
                ('fail_time', models.DateTimeField(blank=True, null=True, verbose_name='支付失败时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='church.Course')),
                ('iap_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.IAPCharge', verbose_name='内购价格')),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PayType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
