# Generated by Django 3.0.3 on 2020-02-25 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_auto_20200216_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_manual_20200222_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.UUIDField(db_index=True, default=uuid.UUID('96ac2619-36be-4b24-ba97-6a3db7b6c5a3'), editable=False, unique=True, verbose_name='订单号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='人民币价格')),
                ('iap_receipt', models.TextField()),
                ('iap_is_sandbox', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '支付失败')], default=0, verbose_name='状态')),
                ('desc', models.CharField(max_length=255, verbose_name='备注')),
                ('fail_time', models.DateTimeField(blank=True, null=True, verbose_name='支付失败时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='church.Course')),
                ('iap_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.IAPCharge', verbose_name='内购价格')),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PayType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
