# Generated by Django 3.0.3 on 2020-03-08 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200304_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7c7f3b5d-d6ca-421a-97d9-e02325b9404d'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
