# Generated by Django 2.2.7 on 2020-03-08 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200308_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('741cbb3f-7af3-4f65-bfc4-2d950877314e'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
