# Generated by Django 2.2.7 on 2020-03-08 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200308_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('fd926a8a-77c9-4d85-ad97-d1323c925acc'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
