# Generated by Django 3.0.3 on 2020-03-15 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200309_0230'),
    ]

    def forwards_func(apps, schema_editor):
        IAPCharge = apps.get_model("payment", "IAPCharge")

        p1 = IAPCharge.objects.get(product_id="com.churchplatform.churchplatform.iap.c.tier2")
        p2 = IAPCharge.objects.get(product_id="com.churchplatform.churchplatform.iap.c.tier15")
        p3 = IAPCharge.objects.get(product_id="com.churchplatform.churchplatform.iap.c.tier66")
        p4 = IAPCharge.objects.get(product_id="com.churchplatform.churchplatform.iap.c.tier81")
        p1.price = 12.00
        p2.price = 98.00
        p3.price = 998.00
        p4.price = 2998.00
        
        p1.price_usd = 1.99
        p2.price_usd = 14.99
        p3.price_usd = 149.99
        p4.price_usd = 449.99
        
        p1.save()
        p2.save()
        p3.save()
        p4.save()
        
    operations = [
        migrations.AddField(
            model_name='iapcharge',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='美元价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('b331161e-9819-4608-a399-12116ff1916e'), editable=False, unique=True, verbose_name='订单号'),
        ),
        migrations.RunPython(forwards_func),
    ]
