# Generated by Django 2.2.7 on 2020-03-27 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200315_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('dbda79b8-c350-4cd4-a2a7-022cbc0dbf99'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
