# Generated by Django 2.2.7 on 2020-04-04 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200327_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ae9e829e-f590-46b7-85aa-0a3cf1ad9940'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
