# Generated by Django 2.2.7 on 2020-04-04 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200404_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('078777a3-ad71-4a50-a6b0-ef9ac67f9fe8'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
