# Generated by Django 2.2.7 on 2020-04-06 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20200404_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('1446df04-14e5-402b-b434-9eb083f069b9'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
