# Generated by Django 2.2.7 on 2020-04-15 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20200407_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(db_index=True, default=uuid.UUID('215494fb-14f1-4fa7-9f62-9f0d71b1fc75'), editable=False, unique=True, verbose_name='订单号'),
        ),
    ]
