# Generated by Django 3.0.3 on 2020-04-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20200415_1712'),
        ('payment', '0019_auto_20200414_2142'),
    ]

    operations = [
    ]
