# Generated by Django 2.2.7 on 2019-12-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='church',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='churchs.Church'),
        ),
    ]
