# Generated by Django 2.2.7 on 2019-12-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191208_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '会友'},
        ),
    ]
