# Generated by Django 2.2.7 on 2019-12-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191209_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '会友', 'verbose_name_plural': '会友'},
        ),
    ]
