# Generated by Django 2.2.7 on 2019-12-14 11:05

import church.storage_backends
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '灵修',
                'verbose_name_plural': '灵修',
            },
        ),
        migrations.CreateModel(
            name='BibleStudyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '灵修评论',
                'verbose_name_plural': '灵修评论',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='图片')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='视频')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='数量')),
                ('pay_type', models.IntegerField(verbose_name='支付类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '奉献',
                'verbose_name_plural': '奉献',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '聚会',
                'verbose_name_plural': '聚会',
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='敬拜')),
                ('pdf', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='讲义')),
                ('scripture', models.CharField(default='', max_length=100, verbose_name='经文')),
                ('cover', models.ImageField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='封面')),
                ('worshipvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='敬拜')),
                ('worshipnote', models.TextField(blank=True, null=True, verbose_name='敬拜歌单')),
                ('mcvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='主持')),
                ('mcnote', models.TextField(blank=True, null=True, verbose_name='主持摘要')),
                ('sermonvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='讲道')),
                ('sermonvnote', models.TextField(blank=True, null=True, verbose_name='讲道摘要')),
                ('givingvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='奉献')),
                ('givingnote', models.TextField(blank=True, null=True, verbose_name='奉献摘要')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '发布')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '主日信息',
                'verbose_name_plural': '主日信息',
            },
        ),
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '下线')], default=2, verbose_name='状态')),
            ],
            options={
                'verbose_name': '讲道系列',
                'verbose_name_plural': '讲道系列',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '讲员',
                'verbose_name_plural': '讲员',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '下线')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '小组',
                'verbose_name_plural': '小组',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('addressUrl', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='封面')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '发布')], default=1, verbose_name='状态')),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
            },
        ),
    ]
