# Generated by Django 2.2.7 on 2019-12-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0002_church_vunue'),
        ('churchs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='team',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='sermonseries',
            name='church',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='sermonseries',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='church',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.SermonSeries', verbose_name='讲道系列'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker', verbose_name='讲员'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑员'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker'),
        ),
        migrations.AddField(
            model_name='donation',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会友信息'),
        ),
        migrations.AddField(
            model_name='course',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='course',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker'),
        ),
        migrations.AddField(
            model_name='biblestudycomment',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='biblestudycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='biblestudy',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker'),
        ),
    ]
