# Generated by Django 2.2.7 on 2019-12-16 04:52

import church.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0002_auto_20191214_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='file2s3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=255, verbose_name='摘要')),
                ('file', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='文件')),
                ('cover', models.ImageField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='封面')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermonfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sermon2s3', to='churchs.file2s3', verbose_name='讲道'),
        ),
    ]
