# Generated by Django 2.2.7 on 2019-12-04 15:15

import church.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_biblestudy_biblestudycomment_course_meeting_speaker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchs', '0002_auto_20191204_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '下线')], default=2)),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32, verbose_name='标题')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='敬拜')),
                ('pdf', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('scripture', models.CharField(default='', max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='图片')),
                ('worshipvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='敬拜')),
                ('mcvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='主持')),
                ('sermonvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='讲道')),
                ('givingvideo', models.FileField(blank=True, null=True, storage=church.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='奉献')),
                ('worshiptext', models.TextField(blank=True, null=True, verbose_name='敬拜')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, '草稿'), (2, '发布')], default=1)),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='churchs.Church')),
                ('series', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.SermonSeries')),
                ('speaker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Speaker')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
