# Generated by Django 2.2.7 on 2019-12-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0003_sermon_sermonseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='worshiptext',
        ),
    ]
