# Generated by Django 2.2.7 on 2019-12-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0004_auto_20191217_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='church',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
    ]
