# Generated by Django 2.2.7 on 2019-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0004_remove_sermon_worshiptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='code',
            field=models.CharField(default='086-010-0001', max_length=32, unique=True),
        ),
    ]
