# Generated by Django 2.2.7 on 2019-12-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0005_church_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': '教会'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': '奉献'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会友'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name': '主日信息'},
        ),
        migrations.AlterModelOptions(
            name='sermonseries',
            options={'verbose_name': '讲道系列'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '小组'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': '场地'},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'verbose_name': '周报'},
        ),
    ]
