# Generated by Django 3.0.1 on 2019-12-23 14:56

import churchs.widget
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0006_auto_20191218_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', churchs.widget.S3DirectField(blank=True)),
                ('image', churchs.widget.S3DirectField(blank=True)),
                ('pdf', churchs.widget.S3DirectField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='givingnote',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='givingvideo',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='mcnote',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='mcvideo',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='sermonfile',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='sermonvideo',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='sermonvnote',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='worshipnote',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='worshipvideo',
        ),
        migrations.AlterField(
            model_name='sermon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='file2s3',
        ),
        migrations.AddField(
            model_name='sermon',
            name='giving_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_giving', to='churchs.Media', verbose_name='奉献'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='mc_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_mc', to='churchs.Media', verbose_name='主持'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermon_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_sermon', to='churchs.Media', verbose_name='讲道'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='worship_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_worship', to='churchs.Media', verbose_name='敬拜'),
        ),
    ]
