# Generated by Django 2.2.7 on 2019-12-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0007_auto_20191209_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': '教会', 'verbose_name_plural': '教会'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会友', 'verbose_name_plural': '会友'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name': '主日信息', 'verbose_name_plural': '主日信息'},
        ),
        migrations.AlterModelOptions(
            name='sermonseries',
            options={'verbose_name': '讲道系列', 'verbose_name_plural': '讲道系列'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': '场地', 'verbose_name_plural': '场地'},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'verbose_name': '周报', 'verbose_name_plural': '周报'},
        ),
    ]
