# Generated by Django 3.0.1 on 2019-12-24 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0007_auto_20191223_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='giving_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_giving', to='churchs.Media', verbose_name='奉献'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='mc_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_mc', to='churchs.Media', verbose_name='主持'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='sermon_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_sermon', to='churchs.Media', verbose_name='讲道'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='worship_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_worship', to='churchs.Media', verbose_name='敬拜'),
        ),
    ]
