# Generated by Django 3.0.1 on 2019-12-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0008_auto_20191224_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '视听媒体', 'verbose_name_plural': '视听媒体'},
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
