# Generated by Django 3.0.1 on 2019-12-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0009_auto_20191224_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='giving_media',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='mc_media',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='sermon_media',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='worship_media',
        ),
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Sermon'),
        ),
    ]
