# Generated by Django 3.0.1 on 2019-12-24 05:58

import churchs.widget
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0011_remove_sermon_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio',
            field=churchs.widget.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='kind',
            field=models.IntegerField(choices=[(1, '敬拜'), (2, '主持'), (3, '讲道'), (4, '奉献'), (5, '其它')], default=3, verbose_name='媒体种类'),
        ),
    ]
