# Generated by Django 3.0.1 on 2019-12-26 04:46

import churchs.widget
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0012_auto_20191224_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_status',
            field=models.IntegerField(choices=[(1, '还没上传媒体'), (2, '媒体已上传'), (3, '媒体已转码发布')], default=1, verbose_name='媒体状态'),
        ),
        migrations.AlterField(
            model_name='media',
            name='audio',
            field=churchs.widget.S3DirectField(blank=True, verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=churchs.widget.S3DirectField(blank=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pdf',
            field=churchs.widget.S3DirectField(blank=True, verbose_name='讲义'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=churchs.widget.S3DirectField(blank=True, verbose_name='视频'),
        ),
    ]
