# Generated by Django 3.0.1 on 2019-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0013_auto_20191226_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='HD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='高清链接'),
        ),
        migrations.AddField(
            model_name='media',
            name='SD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='标清链接'),
        ),
        migrations.AddField(
            model_name='media',
            name='SHD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='超高清链接'),
        ),
    ]
