# Generated by Django 3.0.1 on 2019-12-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0014_auto_20191226_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='churchs.Sermon'),
        ),
    ]
