# Generated by Django 2.2.7 on 2019-12-29 14:13

import churchs.widget
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0015_auto_20191226_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_alioss',
            field=churchs.widget.AliOssDirectField(blank=True, verbose_name='阿里云视频'),
        ),
    ]
