# Generated by Django 2.2.7 on 2020-01-04 05:15

import churchs.widget
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0016_media_video_alioss'),
    ]

    operations = [
        migrations.CreateModel(
            name='ossMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='media',
            old_name='HD_URL',
            new_name='alioss_HD_URL',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='SD_URL',
            new_name='alioss_SD_URL',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='SHD_URL',
            new_name='alioss_SHD_URL',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='video_alioss',
            new_name='alioss_video',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='audio',
            new_name='s3_audio',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='s3_image',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='pdf',
            new_name='s3_pdf',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='video',
            new_name='s3_video',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video_status',
        ),
        migrations.AddField(
            model_name='media',
            name='alioss_audio',
            field=churchs.widget.AliOssDirectField(blank=True, verbose_name='音频'),
        ),
        migrations.AddField(
            model_name='media',
            name='alioss_image',
            field=churchs.widget.AliOssDirectField(blank=True, verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='media',
            name='alioss_pdf',
            field=churchs.widget.AliOssDirectField(blank=True, verbose_name='讲义'),
        ),
        migrations.AddField(
            model_name='media',
            name='alioss_video_status',
            field=models.IntegerField(choices=[(1, '还没上传媒体'), (2, '媒体已上传'), (3, '媒体已转码发布')], default=1, verbose_name='Aliyun媒体状态'),
        ),
        migrations.AddField(
            model_name='media',
            name='s3_HD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='高清链接'),
        ),
        migrations.AddField(
            model_name='media',
            name='s3_SD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='标清链接'),
        ),
        migrations.AddField(
            model_name='media',
            name='s3_SHD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='超高清链接'),
        ),
        migrations.AddField(
            model_name='media',
            name='s3_video_status',
            field=models.IntegerField(choices=[(1, '还没上传媒体'), (2, '媒体已上传'), (3, '媒体已转码发布')], default=1, verbose_name='S3媒体状态'),
        ),
    ]
