# Generated by Django 2.2.7 on 2020-01-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0019_auto_20200111_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='contenttypes.ContentType'),
        ),
    ]
