# Generated by Django 2.2.7 on 2020-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0021_remove_media_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alioss_HD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='Aliyun oss 标清链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_SD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='Aliyun oss 流畅链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_SHD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='Aliyun oss 高清链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.IntegerField(choices=[(1, '敬拜'), (2, '主持'), (3, '讲道'), (4, '奉献'), (5, '课程'), (6, '其它')], default=3, verbose_name='媒体种类'),
        ),
    ]
