# Generated by Django 2.2.7 on 2020-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_auto_20200118_1426'),
        ('churchs', '0022_auto_20200112_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='church',
        ),
        migrations.AddField(
            model_name='speaker',
            name='churchs',
            field=models.ManyToManyField(blank=True, default=None, to='church.Church', verbose_name='教会'),
        ),
    ]
