# Generated by Django 2.2.7 on 2020-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0023_auto_20200118_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ossMedia',
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
    ]
