# Generated by Django 2.2.7 on 2020-02-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0024_auto_20200209_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alioss_HD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='标清链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_SD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='流畅链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_SHD_URL',
            field=models.CharField(blank=True, max_length=400, verbose_name='高清链接'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_video_status',
            field=models.IntegerField(choices=[(1, '还没上传媒体'), (2, '媒体已上传'), (3, '媒体已转码发布')], default=1, verbose_name='视频状态'),
        ),
    ]
