# Generated by Django 3.0.3 on 2020-02-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0026_auto_20200216_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='scripture',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='经文'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.SermonSeries', verbose_name='讲道系列'),
        ),
    ]
