# Generated by Django 3.0.3 on 2020-03-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0027_auto_20200222_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alioss_audio',
            field=models.CharField(blank=True, max_length=400, verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_image',
            field=models.CharField(blank=True, max_length=400, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_pdf',
            field=models.CharField(blank=True, max_length=400, verbose_name='讲义'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_video',
            field=models.CharField(blank=True, max_length=400, verbose_name='视频'),
        ),
    ]
