# Generated by Django 3.0.4 on 2020-03-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0018_auto_20200309_0230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchs', '0028_auto_20200308_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblestudy',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker'),
        ),
        migrations.AlterField(
            model_name='biblestudycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker'),
        ),
        migrations.AlterField(
            model_name='team',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church'),
        ),
    ]
