# Generated by Django 2.2.7 on 2020-04-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0030_auto_20200327_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonseries',
            name='res_path',
            field=models.CharField(default='', max_length=250, verbose_name='资源路径'),
        ),
        migrations.AlterField(
            model_name='sermonseries',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='标题'),
        ),
    ]
