# Generated by Django 2.2.7 on 2020-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0032_auto_20200406_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='profile',
            field=models.CharField(max_length=255, null=True, verbose_name='照片'),
        ),
    ]
