# Generated by Django 2.2.7 on 2020-04-07 12:56

import churchs.widget
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0033_speaker_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='profile',
            field=churchs.widget.AliMediaField(max_length=255, null=True, verbose_name='照片'),
        ),
    ]
