# Generated by Django 2.2.7 on 2020-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0035_auto_20200415_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='church_prefix',
            field=models.CharField(default='', max_length=200, verbose_name='教会存储目录'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='oss存储key'),
        ),
    ]
