# Generated by Django 2.2.7 on 2020-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0036_auto_20200423_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='church_prefix',
            field=models.CharField(default='L3', max_length=200, verbose_name='教会存储目录'),
        ),
    ]
