# Generated by Django 2.2.7 on 2020-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0039_auto_20200424_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='bucket',
            field=models.CharField(default='', max_length=200, verbose_name='桶名称'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='endpoint',
            field=models.CharField(default='', max_length=200, verbose_name='桶地址'),
        ),
    ]
