# Generated by Django 2.2.7 on 2020-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0040_auto_20200424_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='series_prefix',
            field=models.CharField(default='/', max_length=200, verbose_name='教会存储目录'),
        ),
    ]
