# Generated by Django 2.2.7 on 2020-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0042_auto_20200430_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='video_file_tcinfo',
            field=models.CharField(max_length=1000, null=True, verbose_name='视频转码文件'),
        ),
    ]
