# Generated by Django 2.2.7 on 2020-05-03 02:57

import churchs.widget
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0043_auto_20200430_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alioss_image',
            field=churchs.widget.MediaBaseField(blank=True, max_length=400, verbose_name='封面'),
        ),
    ]
