# Generated by Django 2.2.7 on 2020-05-27 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0025_auto_20200527_1023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchs', '0044_auto_20200522_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermonseries',
            options={'verbose_name': '媒体分组', 'verbose_name_plural': '媒体分组'},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'verbose_name': '周报图文', 'verbose_name_plural': '周报图文'},
        ),
        migrations.CreateModel(
            name='ContentColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '下线')], default=2, verbose_name='状态')),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '内容专栏',
                'verbose_name_plural': '内容专栏',
            },
        ),
    ]
