# Generated by Django 2.2.7 on 2020-05-09 01:00

import churchs.widget
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0044_auto_20200503_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', churchs.widget.MediaBaseField(blank=True, max_length=400, verbose_name='封面')),
            ],
        ),
    ]
