# Generated by Django 2.2.7 on 2020-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0045_auto_20200527_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alioss_image',
            field=models.CharField(blank=True, max_length=400, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='media',
            name='alioss_video',
            field=models.CharField(blank=True, max_length=400, verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.IntegerField(choices=[(1, '敬拜'), (2, '主持'), (3, '讲道'), (4, '奉献'), (5, '课程'), (6, '视频'), (7, '音频'), (8, 'PDF'), (9, '其它')], default=3, verbose_name='媒体种类'),
        ),
    ]
