# Generated by Django 2.2.7 on 2020-06-11 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0026_auto_20200529_1244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchs', '0046_auto_20200529_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AddField(
            model_name='media',
            name='church',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会'),
        ),
        migrations.AddField(
            model_name='media',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.IntegerField(choices=[(1, '敬拜'), (2, '主持'), (3, '讲道'), (4, '奉献'), (5, '课程'), (6, '视频'), (7, '音频'), (7, '图文'), (9, 'PDF'), (10, '其它')], default=3, verbose_name='媒体种类'),
        ),
    ]
