# Generated by Django 2.2.7 on 2020-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0047_Media_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcolumn',
            name='medias',
            field=models.ManyToManyField(to='churchs.Media'),
        ),
    ]
