# Generated by Django 2.2.7 on 2020-06-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0048_contentcolumn_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContentColumn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churchs.ContentColumn')),
                ('Media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churchs.Media')),
            ],
        ),
    ]
