# Generated by Django 2.2.7 on 2020-06-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0049_columnmedias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmedias',
            options={'verbose_name': '专栏内容列表', 'verbose_name_plural': '专栏内容列表'},
        ),
        migrations.RemoveField(
            model_name='contentcolumn',
            name='medias',
        ),
        migrations.AddField(
            model_name='media',
            name='column',
            field=models.ManyToManyField(through='churchs.ColumnMedias', to='churchs.ContentColumn'),
        ),
        migrations.AlterField(
            model_name='columnmedias',
            name='ContentColumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchs.ContentColumn'),
        ),
        migrations.AlterField(
            model_name='columnmedias',
            name='Media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='churchs.Media'),
        ),
    ]
