# Generated by Django 2.2.7 on 2020-06-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0050_columnmedia_key_setnull_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcolumn',
            name='medias',
            field=models.ManyToManyField(through='churchs.ColumnMedias', to='churchs.Media'),
        ),
        migrations.AlterField(
            model_name='columnmedias',
            name='ContentColumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn'),
        ),
        migrations.AlterField(
            model_name='columnmedias',
            name='Media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Media'),
        ),
    ]
