# Generated by Django 2.2.7 on 2020-06-18 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0051_columnmedia_key_setnull_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='speaker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Speaker', verbose_name='讲员'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
