# Generated by Django 2.2.7 on 2020-06-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0053_church_lord_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='pub_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
