# Generated by Django 2.2.7 on 2020-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0054_media_add_pubtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='点播次数'),
        ),
    ]
