# Generated by Django 2.2.7 on 2020-06-25 12:41

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_church_lord_swipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churchs', '0055_media_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='vpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='', max_length=250, verbose_name='标题')),
                ('name', models.CharField(default='', max_length=250, verbose_name='名称')),
                ('pub_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('promote_at', models.IntegerField(choices=[(1, 'app首页'), (2, '主日信息首页')], default=1, verbose_name='状态')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '下线')], default=2, verbose_name='状态')),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
                ('create_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微页面',
                'verbose_name_plural': '微页面',
            },
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': '媒体文件', 'verbose_name_plural': '媒体文件'},
        ),
        migrations.CreateModel(
            name='vpage_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('control', models.IntegerField(choices=[(1, 'BANNER'), (2, '小图横滑'), (3, '列表'), (4, '富文本')], default=1, verbose_name='控件')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='摘要')),
                ('ContentColumn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn')),
                ('Media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Media')),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
                ('create_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.vpage')),
            ],
            options={
                'verbose_name': '微组件',
                'verbose_name_plural': '微组件',
            },
        ),
        migrations.CreateModel(
            name='baseChurchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='church.Church', verbose_name='教会')),
                ('create_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教会基础组件',
                'verbose_name_plural': '教会基础组件',
            },
        ),
    ]
