# Generated by Django 2.2.7 on 2020-07-07 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0058_auto_20200629_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmedias',
            options={'ordering': ['order'], 'verbose_name': '专栏内容列表', 'verbose_name_plural': '专栏内容列表'},
        ),
        migrations.AlterField(
            model_name='media',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
