# Generated by Django 2.2.7 on 2020-07-13 07:27

import churchs.widget
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0060_auto_20200713_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcomponents',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='vcomponents',
            name='ContentColumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn', verbose_name='专栏'),
        ),
        migrations.AlterField(
            model_name='vcomponents',
            name='Media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Media', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='vcomponents',
            name='content',
            field=churchs.widget.InlineContentField(blank=True, null=True, verbose_name='富文本'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
