# Generated by Django 2.2.7 on 2020-07-13 09:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0061_vcomp_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcomponents',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='富文本'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
        migrations.CreateModel(
            name='VParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover', models.CharField(blank=True, max_length=400, verbose_name='封面')),
                ('title', models.CharField(default='', max_length=250, verbose_name='标题')),
                ('url', models.CharField(default='', max_length=250, verbose_name='标题')),
                ('css', models.CharField(default='', max_length=500, verbose_name='样式')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('components', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VComponents')),
            ],
        ),
    ]
