# Generated by Django 2.2.7 on 2020-07-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0063_ziliao_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
        migrations.AlterField(
            model_name='vparts',
            name='css',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='样式'),
        ),
        migrations.AlterField(
            model_name='vparts',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='标题'),
        ),
    ]
