# Generated by Django 2.2.7 on 2020-07-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0065_vpart_title_css_default1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcolumn',
            name='cover',
            field=models.CharField(blank=True, max_length=400, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
