# Generated by Django 2.2.7 on 2020-07-16 08:53

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0067_add_object_vpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vparts',
            name='url_obj',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
