# Generated by Django 2.2.7 on 2020-08-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0068_vparts_url_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='cover',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
        migrations.AlterField(
            model_name='vparts',
            name='components',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vparts', to='churchs.VComponents'),
        ),
        migrations.CreateModel(
            name='SermonMedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.IntegerField(choices=[(1, '敬拜'), (2, '主持'), (3, '讲道'), (4, '奉献'), (5, '课程'), (10, '其它')], default=3, verbose_name='媒体种类')),
                ('Media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Media')),
                ('Sermon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.Sermon')),
            ],
            options={
                'verbose_name': '讲道内容列表',
                'verbose_name_plural': '讲道内容列表',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='sermon1',
            field=models.ManyToManyField(through='churchs.SermonMedias', to='churchs.Sermon'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='medias',
            field=models.ManyToManyField(related_name='belong_sermons', through='churchs.SermonMedias', to='churchs.Media'),
        ),
    ]
