# Generated by Django 2.2.7 on 2020-08-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0070_sermon2Medias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon2medias',
            options={'ordering': ['order'], 'verbose_name': '讲道和内容关系表', 'verbose_name_plural': '讲道和内容关系表'},
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
