# Generated by Django 2.2.7 on 2020-08-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0072_Sermon2Medias_addcolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon2medias',
            name='kind',
        ),
        migrations.AlterField(
            model_name='sermon2medias',
            name='fromColumn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn', verbose_name='选自专栏'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
