# Generated by Django 2.2.7 on 2020-09-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0074_speaker_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcolumn',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=400, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
