# Generated by Django 2.2.7 on 2020-10-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0076_column_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcolumn',
            name='parentColumn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn', verbose_name='父专栏'),
        ),
        migrations.AlterField(
            model_name='vpagecomponents',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.VPage'),
        ),
    ]
