# Generated by Django 2.2.7 on 2020-10-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0078_add_column_hier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpage',
            name='church',
        ),
        migrations.RemoveField(
            model_name='vpage',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='vpagecomponents',
            name='components',
        ),
        migrations.RemoveField(
            model_name='vpagecomponents',
            name='page',
        ),
        migrations.RemoveField(
            model_name='vparts',
            name='components',
        ),
        migrations.DeleteModel(
            name='VComponents',
        ),
        migrations.DeleteModel(
            name='vpage',
        ),
        migrations.DeleteModel(
            name='VPageComponents',
        ),
        migrations.DeleteModel(
            name='VParts',
        ),
    ]
