# Generated by Django 2.2.7 on 2020-10-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0079_delete_vpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcolumn',
            old_name='parentColumn',
            new_name='parentCol',
        ),
    ]
