# Generated by Django 2.2.7 on 2020-10-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0082_auto_20201020_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcolumn',
            name='parentCol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churchs.ContentColumn', verbose_name='父专栏'),
        ),
    ]
